version: '3.4'

services:
  app:
    build:
      context: .
      target: development
      args:
        DOCKER_USER: ${DOCKER_USER:-1000}
    user: ${DOCKER_USER:-1000}
    image: fundocker/ralph:development
    env_file:
      - .env
    environment:
      PYLINTHOME: /app/.pylint.d
    ports:
      - "${RALPH_RUNSERVER_PORT:-8100}:${RALPH_RUNSERVER_PORT:-8100}"
    volumes:
      - .:/app

  # -- backends
  elasticsearch:
    image: elasticsearch:8.1.0
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
    ports:
      - "9200:9200"
    mem_limit: 2g

  mongo:
    image: mongo:5.0.9
    ports:
      - "27017:27017"

  swift:
    image: kklopfenstein/openstack-swift-keystone-docker
    ports:
      - "49177:8080"
      - "49178:35357"
    environment:
      KS_SWIFT_PUBLIC_URL: http://127.0.0.1:49177

  graylog:
    image: graylog/graylog:4.2.2
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=d74ff0ee8da3b9806b18c877dbf29bbde50b5bd8e4dad7a3a725000feb82e8f1
      - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:9000/
      - GRAYLOG_ROTATION_STRATEGY=count
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    networks:
      default:
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # GELF TCP
      - 12201:12201

  # -- tools
  dockerize:
    image: jwilder/dockerize
