#
# Ralph package
#
[build-system]
requires = ["setuptools>=42", "wheel", "langcodes>=3.2.0", "pydantic[dotenv,email]>=1.10.0", "rfc3987>=1.3.0","importlib-metadata==6.6.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ralph-malph"
description = "The ultimate toolbox for your learning analytics"
readme = "README.md"
authors = [
  { name="Open FUN (France Universite Numerique)", email="fun.dev@fun-mooc.fr" },
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
requires-python = ">=3.7"
license = {file = "LICENSE.md"}
keywords = ["Open edX", "Analytics", "xAPI", "LRS"]
dynamic = ["version"]

[project.urls]
"Homepage" = "https://github.com/openfun/ralph"
"Bug Tracker" = "https://github.com/openfun/ralph/issues"

#[project.options]
#include_package_data = true
#package_dir = "src"
#packages = "find:"
#zip_safe = true

[project.optional-dependencies]
backend-clickhouse = [
    "clickhouse-connect[numpy,pandas]<0.6",
    "python-dateutil>=2.8.2"
]
backend-es = [
    "elasticsearch>=8.0.0"
]
backend-ldp = [
    "ovh>=1.0.0",
    "requests>=2.0.0"
]
backend-mongo = [
    "pymongo[srv]>=4.0.0",
    "python-dateutil>=2.8.2"
]
backend-s3 = [
    "boto3>=1.24.70",
    "botocore>=1.27.71"
]
backend-swift = [
    "python-keystoneclient>=5.0.0",
    "python-swiftclient>=4.0.0"
]
backend-ws = [
    "websockets>=10.3"
]
cli = [
    "bcrypt>=4.0.0",
    "click>=8.1.0",
    "click-option-group>=0.5.0",
    "sentry-sdk[fastapi]>=1.9.0"
]
dev = [
    "bandit[toml]==1.7.5",
    "black==23.3.0",
    "factory-boy==3.2.1",
    "Faker==18.4.0",
    "flake8==6.0.0",
    "hypothesis==6.72.2",
    "ipdb==0.13.13",
    "ipython==8.12.0",
    "isort==5.12.0",
    "logging-gelf==0.0.26",
    "memory-profiler==0.61.0",
    "mkdocs==1.4.2",
    "mkdocs-click==0.8.0",
    "mkdocs-material==9.1.7",
    "mkdocstrings[python-legacy]==0.21.2",
    "moto==4.1.8",
    "pydocstyle==6.3.0",
    "pyfakefs==5.2.2",
    "pylint==2.17.2",
    "pytest==7.3.1",
    "pytest-asyncio==0.21.0",
    "pytest-cov==4.0.0"
]
ci = [
    "twine==4.0.2"
]
lrs = [
    "bcrypt==4.0.1",
    "fastapi==0.95.1",
    # We temporary pin `h11` to avoid pip downloading the latest version to solve a
    # dependency conflict caused by `httpx` which requires httpcore>=0.15.0,<0.16.0 and
    # `httpcore` depends on h11>=0.11,<0.13.
    # See: https://github.com/encode/httpx/issues/2244
    "h11>=0.11.0",
    "httpx==0.24.0",
    "sentry_sdk==1.20.0",
    "uvicorn[standard]==0.21.1"
]

#[options.packages.find]
#where = "src"

[options.entry_points]
console_scripts = [
  "ralph = ralph.__main__:cli.cli"
]


# Third-party packages configuration
[tool.distutils.bdist_wheel]
universal = true

[tool.setuptools.dynamic]
version = { attr = "ralph.__version__" }

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203"]
exclude = [
    ".git",
    ".venv",
    "build",
    "venv",
    "__pycache__",
    "node_modules",
    "*/migrations/*"
]

[tool.pydocstyle]
convention = "google"
match_dir = "^(?!tests|venv|build|scripts).*"
#match = "^(?!(setup)\.(py)$).*\.(py)$"

[tool.isort]
known_ralph = ["ralph"]
sections= [
    "FUTURE",
    "STDLIB",
    "THIRDPARTY",
    "RALPH",
    "FIRSTPARTY",
    "LOCALFOLDER"
]
skip_glob=["venv"]
profile="black"

[tool.pytest.ini_options]
addopts = "-v --cov-report term-missing --cov-config=.coveragerc --cov=ralph --cov=plugins"
python_files = [
    "test_*.py",
    "tests.py",
]
testpaths = [
    "tests",
    "plugins"
]

[tool.bandit]
exclude_dirs = ["tests",]